# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '16.0'
project '../DawnKeyManagerFW.xcodeproj'

target 'DawnKeyManagerFW' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'DawnKeyManagerFW', path: '../'

  # Pods for DawnKeyManagerFW

  target 'DawnKeyManagerFWTests' do
    # Pods for testing
  end

end

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example

end
